In [1]:
%matplotlib widget
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [4]:
clean_gme = 'Data/Combined GME Hourly Data.csv'
gme_df = pd.read_csv(clean_gme)
gme_df.head(20)

,time,open,high,low,close,volume,Close - Open (Round to 2deci),High - Low (Round to 2deci)
0,2/2/2021 20:00,90.0000,90.5000,85.0000,85.2000,288108,-4.80,5.50
1,2/2/2021 19:00,92.0000,94.0000,88.0000,90.0000,232127,-2.00,6.00
2,2/2/2021 18:00,88.8200,96.0000,86.0100,92.0000,476352,3.18,9.99
3,2/2/2021 17:00,90.7600,93.8900,85.3300,88.7800,843580,-1.98,8.56
4,2/2/2021 16:00,99.8561,101.9599,88.0000,90.4700,5582379,-9.39,13.96
5,2/2/2021 15:00,103.6001,110.5499,91.0000,99.9000,6042536,-3.70,19.55
6,2/2/2021 14:00,118.2996,118.7500,101.0100,104.3724,4486108,-13.93,17.74
7,2/2/2021 13:00,110.0500,127.9800,105.1700,117.9500,7738481,7.90,22.81
8,2/2/2021 12:00,91.0701,154.3999,90.0000,114.8500,15756996,23.78,64.40
9,2/2/2021 11:00,114.8882,125.0000,74.2201,91.5000,19988224,-23.39,50.78
10,2/2/2021 10:00,127.5000,162.0000,101.3000,115.0000,13083953,-12.50,60.70
11,2/2/2021 9:00,139.0000,161.0000,126.0000,127.5000,1956246,-11.50,35.00
12,2/2/2021 8:00,158.2400,162.6500,137.0100,138.7000,1521962,-19.54,25.64
13,2/2/2021 7:00,174.0100,175.2100,153.6000,158.4900,179575,-15.52,21.61
14,2/2/2021 6:00,171.7000,176.3900,170.0000,174.5000,79576,2.80,6.39
15,2/2/2021 5:00,175.3000,178.3100,160.0000,171.0000,246548,-4.30,18.31
16,2/1/2021 20:00,186.6500,198.9900,186.6500,189.5200,398808,2.87,12.34
17,2/1/2021 19:00,178.0000,190.0000,177.0000,187.7500,495863,9.75,13.00
18,2/1/2021 18:00,207.9600,208.7900,173.0000,178.0000,1577886,-29.96,35.79
19,2/1/2021 17:00,225.4600,231.0000,206.0000,207.5500,626967,-17.91,25.00

In [11]:
vol_gme = plt.bar(gme_df['time'], gme_df["volume"])
vol_gme.set_xlabel("Date&Time")
vol_gme.set_ylabel('Volume (1E8)')
plt.show()

AttributeError: 'BarContainer' object has no attribute 'set_xlabel'